### ISSUE TITLE
i dont get geoip to work

### ISSUE THREAD

**Issue by groeneveldgert** [jpgamboa/geoip-example#1]
hey jagamboa,
Thanks for the script! It works great on our website www.walterwallet.com with the redirects you made. But unfortunately I can't get it to work with my own redirects. Can you help me with this?
Our website is hosted on wpengine and it also runs through cloudflare. Below you can see how I changed your script.

<?php
/*
Plugin Name: John Gamboa's GeoIP Redirect Example
Description: Redirecting visitor traffic based on geo-location using the WPEngine GEO IP feature
Version: 1.0
License: GPLv2
*/
function country_geo_redirect() {
$country = getenv('HTTP_GEOIP_COUNTRY_CODE');
if ( $country == "DE" ) {
wp_redirect( 'https://walterwallet.com/kaufen/?lang=de', 301 );
     exit;
} else if ( $country == "FR" ) {
wp_redirect( 'https://walterwallet.com/acheter/?lang=fr', 301 );
     exit;

} else if ( $country == "GB" ) {
wp_redirect( 'https://walterwallet.com/waltershop/?lang=ep', 301 );
     exit;

}else if ( $country !== "(DE|FR|GB)" ) {
wp_redirect( 'https://walterwallet.com', 301 );
     exit;
}
}
add_action('init', 'country_geo_redirect');

**Comment by jpgamboa** [comment]
Hey there!

I still work at WP Engine and I tried to take a look at your configuration
on your server but didn't see the script added to the walterwallet.com
WordPress install. I do see that you have CloudFlare enabled on this site.
It might be worth putting it in development mode when testing to see if it
will make a difference. If you can give me some more info, and possible
point to a live example, I might be able to glean some additional data.

**Comment by groeneveldgert** [comment]
hey John,
Thanks for the quick answer!

You are right. I tested your code again with our url's on the staging
environment of www.walterwallet.com and it worked like a charm. (see code
below)
Do you have an idea how to get it to work with cloudflare?

Please let me know what more info you need. We are happy to give you as
much info as you need to get it to work :-)

Thanks in advance!

Best,
Gert

<?php
/*
Plugin Name: John Gamboa's GeoIP Redirect Example
Description: Redirecting visitor traffic based on geo-location using the
WPEngine GEO IP feature
Version: 1.0
License: GPLv2
*/
function country_geo_redirect() {
$country = getenv('HTTP_GEOIP_COUNTRY_CODE');
if ( $country == "DE" ) {
wp_redirect( 'https://walterwallet.com/kaufen/?lang=de', 301 );
     exit;
} else if ( $country == "FR" ) {
wp_redirect( 'https://walterwallet.com/acheter/?lang=fr', 301 );
     exit;

} else if ( $country == "GB" ) {
wp_redirect( 'https://walterwallet.com/waltershop/?lang=ep', 301 );
     exit;

}else if ( $country !== "(DE|FR|GB)" ) {
wp_redirect( 'https://walterwallet.com', 301 );
     exit;
}
}
add_action('init', 'country_geo_redirect');

2016-06-30 23:44 GMT+02:00 John P. Gamboa notifications@github.com:

**Comment by groeneveldgert** [comment]
I got an answer from cloudflare and they say that I could try and change
$country = getenv('HTTP_GEOIP_COUNTRY_CODE');
change with:
$country = $_SERVER["HTTP_CF_IPCOUNTRY"];

But that doesn't seem to do the trick. Can you help me out?
Gert

2016-07-01 9:57 GMT+02:00 Gert Groeneveld | Knowidea gert@knowidea.nl:

**Comment by jpgamboa** [comment]
Hey there,

I use CloudFlare on my own site to run GeoIP with this code. I would
recommend that you add the plugin, purge your WP Engine cache, then log
into CloudFlare, go to Caching, click Purge Individual Files on the drop
down and click "Purge Everything." That should get the plugin working. Let
me know how that goes!

**Comment by groeneveldgert** [comment]
hey John,

Thanks for the help!
Unfortunately this doesn't work. I am not sure what goes wrong. These are
the steps I take:
- uploaded the geoip.php file to the wp-content/mu-plugin folder
- cleared the wpengine cache in wordpress - here I already get a message
  that the website is in a loop

If I do it with these steps:
- uploaded the geoip.php file to the wp-content/mu-plugin folder
- cleared the cloudflare cache
- cleared the wpengine cache in wordpress - here I already get a message
  that the website is in a loop

Am I inserting the geoip.php file in the correct folder?
Or maybe my url's are not correct?
Can you take another look at it?

Thanks in advance!

Gert

---------- Forwarded message ----------
